export const POPULAR_MOVIES = 'POPULAR_MOVIES';
export const LATEST_MOVIES = 'LATEST_MOVIES';
export const POPULAR_SHOWS = 'POPULAR_SHOWS';
export const UPCOMING_MOVIES = 'UPCOMING_MOVIES';
export const TOP_RATED_MOVIES = 'TOP_RATED_MOVIES';
